# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_region', to='assistant.Region', verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d'),
        ),
    ]
